# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 700)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(700, 700))
        MainWindow.setMaximumSize(QSize(700, 700))
        icon = QIcon()
        icon.addFile(u":/newPrefix/images/appicon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btn_Quit = QPushButton(self.centralwidget)
        self.btn_Quit.setObjectName(u"btn_Quit")
        self.btn_Quit.setGeometry(QRect(6, 631, 131, 35))
        self.btn_Quit.setFocusPolicy(Qt.StrongFocus)
        self.btn_Quit.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/newPrefix/images/Application-exit-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_Quit.setIcon(icon1)
        self.btn_Check = QPushButton(self.centralwidget)
        self.btn_Check.setObjectName(u"btn_Check")
        self.btn_Check.setGeometry(QRect(560, 631, 131, 35))
        self.btn_Check.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u":/newPrefix/images/Refresh-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_Check.setIcon(icon2)
        self.btn_Check.setAutoDefault(False)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QRect(140, 581, 551, 30))
        self.progressBar.setStyleSheet(u"")
        self.progressBar.setValue(24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.lbl_task = QLabel(self.centralwidget)
        self.lbl_task.setObjectName(u"lbl_task")
        self.lbl_task.setGeometry(QRect(10, 585, 121, 20))
        self.lbl_task.setStyleSheet(u"")
        self.lbl_available = QLabel(self.centralwidget)
        self.lbl_available.setObjectName(u"lbl_available")
        self.lbl_available.setGeometry(QRect(6, 25, 645, 20))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_available.setFont(font)
        self.lbl_available.setAlignment(Qt.AlignCenter)
        self.btn_about = QToolButton(self.centralwidget)
        self.btn_about.setObjectName(u"btn_about")
        self.btn_about.setGeometry(QRect(657, 10, 35, 35))
        icon3 = QIcon()
        icon3.addFile(u":/newPrefix/images/Information-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_about.setIcon(icon3)
        self.btn_about.setIconSize(QSize(24, 24))
        self.btn_about.setCheckable(False)
        self.btn_about.setChecked(False)
        self.frm_start = QFrame(self.centralwidget)
        self.frm_start.setObjectName(u"frm_start")
        self.frm_start.setGeometry(QRect(6, 50, 686, 271))
        self.frm_start.setFrameShape(QFrame.StyledPanel)
        self.frm_start.setFrameShadow(QFrame.Raised)
        self.lbl_start = QLabel(self.frm_start)
        self.lbl_start.setObjectName(u"lbl_start")
        self.lbl_start.setGeometry(QRect(90, 70, 491, 41))
        self.lbl_start.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_start.setWordWrap(True)
        self.line_path = QLineEdit(self.frm_start)
        self.line_path.setObjectName(u"line_path")
        self.line_path.setGeometry(QRect(80, 160, 491, 35))
        self.btn_path = QToolButton(self.frm_start)
        self.btn_path.setObjectName(u"btn_path")
        self.btn_path.setGeometry(QRect(576, 160, 35, 35))
        icon4 = QIcon()
        icon4.addFile(u":/newPrefix/images/Open-folder-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_path.setIcon(icon4)
        self.label = QLabel(self.frm_start)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 130, 311, 20))
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label.setWordWrap(True)
        self.btn_cancel = QPushButton(self.centralwidget)
        self.btn_cancel.setObjectName(u"btn_cancel")
        self.btn_cancel.setGeometry(QRect(110, 585, 24, 24))
        icon5 = QIcon()
        icon5.addFile(u":/newPrefix/images/Cancel-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cancel.setIcon(icon5)
        self.frm_progress = QFrame(self.centralwidget)
        self.frm_progress.setObjectName(u"frm_progress")
        self.frm_progress.setGeometry(QRect(6, 50, 686, 251))
        self.frm_progress.setStyleSheet(u"")
        self.frm_progress.setFrameShape(QFrame.StyledPanel)
        self.frm_progress.setFrameShadow(QFrame.Raised)
        self.lbl_download_pic = QLabel(self.frm_progress)
        self.lbl_download_pic.setObjectName(u"lbl_download_pic")
        self.lbl_download_pic.setGeometry(QRect(40, 50, 24, 24))
        self.lbl_extract_pic = QLabel(self.frm_progress)
        self.lbl_extract_pic.setObjectName(u"lbl_extract_pic")
        self.lbl_extract_pic.setGeometry(QRect(40, 80, 24, 24))
        self.lbl_copy_pic = QLabel(self.frm_progress)
        self.lbl_copy_pic.setObjectName(u"lbl_copy_pic")
        self.lbl_copy_pic.setGeometry(QRect(40, 110, 24, 24))
        self.lbl_downloading = QLabel(self.frm_progress)
        self.lbl_downloading.setObjectName(u"lbl_downloading")
        self.lbl_downloading.setGeometry(QRect(70, 50, 561, 24))
        self.lbl_downloading.setStyleSheet(u"")
        self.lbl_extraction = QLabel(self.frm_progress)
        self.lbl_extraction.setObjectName(u"lbl_extraction")
        self.lbl_extraction.setGeometry(QRect(70, 80, 221, 24))
        self.lbl_copying = QLabel(self.frm_progress)
        self.lbl_copying.setObjectName(u"lbl_copying")
        self.lbl_copying.setGeometry(QRect(70, 110, 181, 24))
        self.lbl_clean_pic = QLabel(self.frm_progress)
        self.lbl_clean_pic.setObjectName(u"lbl_clean_pic")
        self.lbl_clean_pic.setGeometry(QRect(40, 140, 24, 24))
        self.lbl_cleanup = QLabel(self.frm_progress)
        self.lbl_cleanup.setObjectName(u"lbl_cleanup")
        self.lbl_cleanup.setGeometry(QRect(70, 140, 171, 24))
        self.btngrp_filter = QGroupBox(self.centralwidget)
        self.btngrp_filter.setObjectName(u"btngrp_filter")
        self.btngrp_filter.setGeometry(QRect(200, 605, 307, 61))
        self.btn_osx = QToolButton(self.btngrp_filter)
        self.btn_osx.setObjectName(u"btn_osx")
        self.btn_osx.setGeometry(QRect(227, 30, 75, 23))
        self.btn_osx.setStyleSheet(u"")
        icon6 = QIcon()
        icon6.addFile(u":/newPrefix/images/Apple-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_osx.setIcon(icon6)
        self.btn_osx.setCheckable(True)
        self.btn_osx.setAutoExclusive(True)
        self.btn_windows = QToolButton(self.btngrp_filter)
        self.btn_windows.setObjectName(u"btn_windows")
        self.btn_windows.setGeometry(QRect(79, 30, 75, 23))
        self.btn_windows.setAutoFillBackground(False)
        icon7 = QIcon()
        icon7.addFile(u":/newPrefix/images/Windows-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_windows.setIcon(icon7)
        self.btn_windows.setCheckable(True)
        self.btn_windows.setAutoExclusive(True)
        self.btn_allos = QToolButton(self.btngrp_filter)
        self.btn_allos.setObjectName(u"btn_allos")
        self.btn_allos.setGeometry(QRect(5, 30, 75, 23))
        self.btn_allos.setStyleSheet(u"")
        self.btn_allos.setCheckable(True)
        self.btn_allos.setChecked(True)
        self.btn_allos.setAutoExclusive(True)
        self.btn_linux = QToolButton(self.btngrp_filter)
        self.btn_linux.setObjectName(u"btn_linux")
        self.btn_linux.setGeometry(QRect(153, 30, 75, 23))
        icon8 = QIcon()
        icon8.addFile(u":/newPrefix/images/Linux-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_linux.setIcon(icon8)
        self.btn_linux.setCheckable(True)
        self.btn_linux.setAutoExclusive(True)
        self.btn_oneclick = QPushButton(self.centralwidget)
        self.btn_oneclick.setObjectName(u"btn_oneclick")
        self.btn_oneclick.setGeometry(QRect(260, 630, 191, 35))
        self.btn_oneclick.setStyleSheet(u"")
        icon9 = QIcon()
        icon9.addFile(u":/newPrefix/images/Actions-quickopen-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_oneclick.setIcon(icon9)
        self.lbl_quick = QLabel(self.centralwidget)
        self.lbl_quick.setObjectName(u"lbl_quick")
        self.lbl_quick.setGeometry(QRect(290, 610, 131, 20))
        self.lbl_quick.setAlignment(Qt.AlignCenter)
        self.lbl_caution = QLabel(self.centralwidget)
        self.lbl_caution.setObjectName(u"lbl_caution")
        self.lbl_caution.setGeometry(QRect(6, 3, 645, 20))
        self.lbl_caution.setFont(font)
        self.lbl_caution.setAutoFillBackground(True)
        self.lbl_caution.setAlignment(Qt.AlignCenter)
        self.btn_newVersion = QPushButton(self.centralwidget)
        self.btn_newVersion.setObjectName(u"btn_newVersion")
        self.btn_newVersion.setGeometry(QRect(500, 10, 151, 35))
        icon10 = QIcon()
        icon10.addFile(u":/newPrefix/images/software-update-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_newVersion.setIcon(icon10)
        self.btn_newVersion.setIconSize(QSize(24, 24))
        self.btn_newVersion.setCheckable(False)
        self.btn_newVersion.setChecked(False)
        self.btn_execute = QPushButton(self.centralwidget)
        self.btn_execute.setObjectName(u"btn_execute")
        self.btn_execute.setGeometry(QRect(260, 630, 191, 40))
        self.btn_execute.setStyleSheet(u"")
        icon11 = QIcon()
        icon11.addFile(u":/newPrefix/images/Blender-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_execute.setIcon(icon11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.btngrp_filter.raise_()
        self.frm_start.raise_()
        self.btn_Quit.raise_()
        self.btn_Check.raise_()
        self.progressBar.raise_()
        self.lbl_task.raise_()
        self.lbl_available.raise_()
        self.btn_about.raise_()
        self.btn_cancel.raise_()
        self.frm_progress.raise_()
        self.btn_oneclick.raise_()
        self.lbl_quick.raise_()
        self.lbl_caution.raise_()
        self.btn_newVersion.raise_()
        self.btn_execute.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.btn_Check.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Overmind Studios BlenderUpdater", None))
        self.btn_Quit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.btn_Check.setText(QCoreApplication.translate("MainWindow", u"Version Check", None))
        self.lbl_task.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lbl_available.setText(QCoreApplication.translate("MainWindow", u"Available versions from buildbot:", None))
#if QT_CONFIG(tooltip)
        self.btn_about.setToolTip(QCoreApplication.translate("MainWindow", u"Settings", None))
#endif // QT_CONFIG(tooltip)
        self.btn_about.setText("")
        self.lbl_start.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Press &quot;Version Check&quot; to get a list of the most current buildbot versions.</p></body></html>", None))
        self.line_path.setText(QCoreApplication.translate("MainWindow", u"not set", None))
        self.btn_path.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Choose path (must be an existing folder):", None))
        self.btn_cancel.setText("")
        self.lbl_download_pic.setText("")
        self.lbl_extract_pic.setText("")
        self.lbl_copy_pic.setText("")
        self.lbl_downloading.setText(QCoreApplication.translate("MainWindow", u"Downloading", None))
        self.lbl_extraction.setText(QCoreApplication.translate("MainWindow", u"Extraction", None))
        self.lbl_copying.setText(QCoreApplication.translate("MainWindow", u"Copying files", None))
        self.lbl_clean_pic.setText("")
        self.lbl_cleanup.setText(QCoreApplication.translate("MainWindow", u"Cleaning up", None))
        self.btngrp_filter.setTitle(QCoreApplication.translate("MainWindow", u"Filter results", None))
        self.btn_osx.setText(QCoreApplication.translate("MainWindow", u"OSX", None))
        self.btn_windows.setText(QCoreApplication.translate("MainWindow", u"Windows", None))
        self.btn_allos.setText(QCoreApplication.translate("MainWindow", u"all OS", None))
        self.btn_linux.setText(QCoreApplication.translate("MainWindow", u"Linux", None))
#if QT_CONFIG(tooltip)
        self.btn_oneclick.setToolTip(QCoreApplication.translate("MainWindow", u"Use last used settings to update blender. Uses the path in the above text field and specified version on the button.", None))
#endif // QT_CONFIG(tooltip)
        self.btn_oneclick.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.lbl_quick.setText(QCoreApplication.translate("MainWindow", u"Quick Update", None))
        self.lbl_caution.setText(QCoreApplication.translate("MainWindow", u" These builds are not as stable as releases, use at your own risk.", None))
#if QT_CONFIG(tooltip)
        self.btn_newVersion.setToolTip(QCoreApplication.translate("MainWindow", u"New version available", None))
#endif // QT_CONFIG(tooltip)
        self.btn_newVersion.setText(QCoreApplication.translate("MainWindow", u"New version available", None))
#if QT_CONFIG(tooltip)
        self.btn_execute.setToolTip(QCoreApplication.translate("MainWindow", u"Run downloaded Blender version", None))
#endif // QT_CONFIG(tooltip)
        self.btn_execute.setText(QCoreApplication.translate("MainWindow", u"Run Blender", None))
    # retranslateUi

